### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by SsuJ-Chang**
章思傑

http://18.213.157.118:3000/
http://18.213.157.118:3000/attraction/4

### CODE REVIEW

**Review by cwpeng — DISMISSED** [review]
OK. Well Done.

**Comment by SsuJ-Chang** [comment]
Complete member system

**Comment by cwpeng** [comment]
I have reviewed, if you want me review again, request again.

**Comment by cwpeng** [comment]
JWT decode() may throw expiration exception. we will catch that and accept it as a non-login status.

**Comment by SsuJ-Chang** [comment]
I've added expiration for JWT, and removed expiration of cookie.

`"exp": datetime.utcnow() + timedelta(minutes=3)`

**Comment by SsuJ-Chang** [comment]
I add expiration of cookie again because cookie should be deleted.

**Review by cwpeng — APPROVED** [review]
OK. Good Try.

**Comment by SsuJ-Chang** [comment]
Add handler for JWT expiration and cookie expiration

**Pull request merged**
