### PR TITLE
Complete Part1

### PR DESCRIPTION
**Pull request by SsuJ-Chang**
章思傑

http://18.213.157.118:3000/api/attractions?page=4
http://18.213.157.118:3000/api/attractions?page=0&keyword=館
http://18.213.157.118:3000/api/attraction/1

### CODE REVIEW

**Comment by cwpeng** [comment]
1. Format of "images" field in response of http://18.213.157.118:3000/api/attraction/1 is not correct.

fix it, create new commit, and leave message for me to review again.

**Comment by SsuJ-Chang** [comment]
章思傑
I've already fixed.
Please check it.

http://18.213.157.118:3000/api/attraction/50

**Comment by cwpeng** [comment]
As I have emphasized, never use id for range selection, neither as count of rows. I mean you have to use other SQL queries to replace current queries listed below:
```
data_cursor.execute("SELECT id FROM `tpe-attractions` ORDER BY id DESC LIMIT 1")
sql="SELECT * FROM `tpe-attractions` WHERE id BETWEEN %s and %s"
```

**Comment by SsuJ-Chang** [comment]
章思傑

Okay, I've adjusted the syntax.

**Review by cwpeng — APPROVED** [review]
OK. Well Done.

**Pull request merged**
