### PR TITLE
Finish index.html, keyword query and scroll fetching

### PR DESCRIPTION
**Pull request by SsuJ-Chang**
章思傑

http://18.213.157.118:3000/

### CODE REVIEW

**Comment by cwpeng** [comment]
Almost done but small text layout issue as screenshot: make 登入/註冊 in a single line.

**Comment by SsuJ-Chang** [comment]
Done!
Check it again, thank you!

http://18.213.157.118:3000/

**Review by cwpeng — CHANGES_REQUESTED** [review]
Declare variable before using it. It's the best practice for the most of programming languages.
```
    src="http://18.213.157.118:3000/api/attractions?keyword="+keywordInput;  // EC2
    // page=0 並清空所有 Array
    page=0;
    imgArr=[];
    nameArr=[];
    mrtArr=[]; 
    categoryArr=[];
```

Re-request me review after correction.

**Comment by SsuJ-Chang** [comment]
I declare those variables in script.js. And I think script.js should be loaded before keyword.js.
If I declare again, my codes cannot work like now...

<script type="text/javascript" src="script.js"></script>
<script type="text/javascript" src="load.js"></script>
<script type="text/javascript" src="keyword.js"></script>

**Comment by cwpeng** [comment]
OK. Good. I miss them.

But, I can approve you, only if I get a review request again.

**Review by cwpeng — APPROVED** [review]
OK Done.

Suggestion: try to fix repeating loading issue if I scroll down, up, down, ... quickly near the bottom of page.

**Pull request merged**
